import React, { createContext, useContext, useMemo, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: 'Kisan Profit Mitra',
    heroTitle: 'Kisan Profit Mitra',
    heroSubtitle: 'Your digital farming diary',
    feature1: 'Track all expenses',
    feature2: 'Calculate profit and loss',
    feature3: 'Keep records for every crop',
    feature4: 'Generate PDF reports',
    ctaStart: 'Get Started',
    ctaLogin: 'Log In',
    footerTagline: 'Built for Indian farmers',

    loginTitle: 'Log In',
    loginSubtitle: 'Access your account',
    mobileLabel: 'Mobile Number',
    mobilePlaceholder: '10-digit number',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter password',
    loginButton: 'Log In',
    loginButtonLoading: 'Logging in...',
    loginError: 'Login error',
    noAccount: "Don’t have an account?",
    signupHere: 'Sign up here',
    backHome: '← Back to home',

    signupTitle: 'Create Account',
    signupSubtitle: 'Register yourself',
    nameLabel: 'Name',
    namePlaceholder: 'Enter your name',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter password',
    signupButton: 'Sign Up',
    signupButtonLoading: 'Signing up...',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    signupError: 'Signup error',
    haveAccount: 'Already have an account?',
    loginHere: 'Log in here',

    welcomeUser: 'Welcome',
    logout: 'Logout',
    startNewCrop: 'Start New Crop',
    activeCrops: 'Active Crops',
    noActiveCrops: 'No active crops. Start one!',
    completedCrops: 'Completed Crops',
    modalTitle: 'Start a new crop',
    selectCrop: 'Choose Crop',
    startDate: 'Start Date',
    expectedDuration: 'Expected Duration (months)',
    landArea: 'Land Area',
    landPlaceholder: 'e.g. 2.5',
    cancel: 'Cancel',
    create: 'Create',
    durationPlaceholder: 'e.g. 4',
    months: 'months',
    startLabel: 'Start',
    viewDetails: 'View Details',
    notAvailable: 'Not available',
    areaValidation: 'Enter a valid land value (>0)',
    durationValidation: 'Enter a valid duration in months',
    createCropError: 'Error creating crop',
    pdfRequiresCompletion: 'Complete the crop before downloading PDF.',
    deleteCropConfirm: 'Are you sure you want to delete this crop?',
    deleteExpenseConfirm: 'Delete this expense?',
    genericError: 'Error',
    expenseDeleteError: 'Error deleting expense',
    quantity: 'Quantity',
    edit: 'Edit',
    quantityPlaceholderExample: 'e.g. 50',
    sellingPricePlaceholderExample: 'e.g. 2000',

    cropInfo: 'Crop Info',
    crop: 'Crop',
    land: 'Land',
    duration: 'Duration',
    status: 'Status',
    financialSummary: 'Financial Summary',
    totalCost: 'Total Cost',
    totalIncome: 'Total Income',
    netProfit: 'Net Profit',
    netLoss: 'Net Loss',
    addExpense: 'Add Expense',
    completeCrop: 'Complete Crop',
    generatePDF: 'Generate PDF',
    deleteCrop: 'Delete Crop',
    expenseDetails: 'Expense Details',
    noExpensesYet: 'No expenses added yet',
    addFirstExpense: 'Add first expense',
    byType: 'Expenses by Type',
    individualExpenses: 'Individual Expenses',
    completeCropTitle: 'Complete Crop',
    productionQty: 'Production (Quantity)',
    unit: 'Unit',
    sellingPrice: 'Selling Price (per unit)',
    complete: 'Complete',
    notFound: 'Crop not found',
    backToDashboard: 'Back to dashboard',
    downloadPdfAfterComplete: 'Complete the crop before downloading PDF',

    addExpenseTitle: 'Add New Expense',
    editExpenseTitle: 'Edit Expense',
    backToCropDetails: 'Crop Details',
    dateLabel: 'Date',
    materialTypeLabel: 'Material Type',
    materialNameLabel: 'Material Name',
    tractorOwnerLabel: 'Tractor Owner Name',
    materialNamePlaceholder: 'e.g. Urea, DAP, Labor etc.',
    tractorOwnerPlaceholder: 'e.g. Ram Singh',
    hoursLabel: 'Hours',
    personsLabel: 'Persons',
    quantityLabel: 'Quantity',
    quantityPlaceholder: 'e.g. 50',
    tractorHoursPlaceholder: 'e.g. 2.5',
    unitLabel: 'Unit',
    numberOfDaysLabel: 'Number of Days',
    daysPlaceholder: 'e.g. 5',
    pricePerHourLabel: 'Rate per Hour (₹)',
    pricePerPersonLabel: 'Rate per Person (₹)',
    pricePerUnitLabel: 'Price per Unit (₹)',
    pricePlaceholder: 'e.g. 250',
    totalAmountLabel: 'Total Amount',
    laborTypeLabel: 'Labor Type',
    billPhotoLabel: 'Bill Photo (Optional)',
    billPhotoHelp: 'JPG, PNG, or PDF (max 5MB)',
    notesLabel: 'Notes (Optional)',
    notesPlaceholder: 'Any additional information...',
    addExpenseButton: 'Add Expense',
    addingExpenseButton: 'Adding...',
    updateExpenseButton: 'Update Expense',
    updatingExpenseButton: 'Updating...',
    fileSizeError: 'File must not exceed 5MB',
    quantityValidationError: 'Quantity must be greater than 0',
    priceValidationError: 'Price per unit must be greater than 0',
    addExpenseError: 'Error adding expense',
    updateExpenseError: 'Error updating expense',
    loadExpenseError: 'Error loading expense',
    days: 'days'
  },
  hi: {
    appName: 'किसान प्रॉफिट मित्र',
    heroTitle: 'किसान प्रॉफिट मित्र',
    heroSubtitle: 'आपकी डिजिटल खेती डायरी',
    feature1: 'खर्च का पूरा हिसाब रखें',
    feature2: 'लाभ-हानि की गणना करें',
    feature3: 'सभी फसलों का रिकॉर्ड',
    feature4: 'PDF रिपोर्ट बनाएं',
    ctaStart: 'शुरू करें',
    ctaLogin: 'लॉगिन करें',
    footerTagline: 'भारतीय किसानों के लिए बनाया गया',

    loginTitle: 'लॉगिन करें',
    loginSubtitle: 'अपने खाते में प्रवेश करें',
    mobileLabel: 'मोबाइल नंबर',
    mobilePlaceholder: '10 अंकों का नंबर',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: 'पासवर्ड डालें',
    loginButton: 'लॉगिन करें',
    loginButtonLoading: 'लॉगिन हो रहा है...',
    loginError: 'लॉगिन में त्रुटि',
    noAccount: 'खाता नहीं है?',
    signupHere: 'यहाँ पंजीकरण करें',
    backHome: '← होम पेज पर वापस जाएं',

    signupTitle: 'नया खाता बनाएं',
    signupSubtitle: 'अपना पंजीकरण करें',
    nameLabel: 'नाम',
    namePlaceholder: 'अपना नाम डालें',
    confirmPasswordLabel: 'पासवर्ड दोबारा डालें',
    confirmPasswordPlaceholder: 'पासवर्ड दोबारा डालें',
    signupButton: 'पंजीकरण करें',
    signupButtonLoading: 'पंजीकरण हो रहा है...',
    passwordMismatch: 'पासवर्ड मेल नहीं खाते',
    passwordTooShort: 'पासवर्ड कम से कम 6 अक्षर का होना चाहिए',
    signupError: 'पंजीकरण में त्रुटि',
    haveAccount: 'पहले से खाता है?',
    loginHere: 'यहाँ लॉगिन करें',

    welcomeUser: 'स्वागत है',
    logout: 'लॉगआउट',
    startNewCrop: 'नई फसल शुरू करें',
    activeCrops: 'चालू फसलें',
    noActiveCrops: 'कोई चालू फसल नहीं है। नई फसल शुरू करें!',
    completedCrops: 'पूर्ण फसलें',
    modalTitle: 'नई फसल शुरू करें',
    selectCrop: 'फसल चुनें (Crop)',
    startDate: 'शुरुआत की तारीख',
    expectedDuration: 'अनुमानित अवधि (महीने)',
    landArea: 'जमीन का क्षेत्रफल',
    landPlaceholder: 'जैसे: 2.5',
    cancel: 'रद्द करें',
    create: 'बनाएं',
    durationPlaceholder: 'जैसे: 4',
    months: 'महीने',
    startLabel: 'शुरुआत',
    viewDetails: 'विवरण देखें →',
    notAvailable: 'उपलब्ध नहीं',
    areaValidation: 'जमीन का मान सही भरें (0 से ऊपर)',
    durationValidation: 'अवधि महीनों में सही भरें',
    createCropError: 'फसल बनाने में त्रुटि',
    pdfRequiresCompletion: 'फसल पूर्ण करने के बाद ही PDF डाउनलोड की जा सकती है।',
    deleteCropConfirm: 'क्या आप वाकई इस फसल को हटाना चाहते हैं?',
    deleteExpenseConfirm: 'क्या आप इस खर्च को हटाना चाहते हैं?',
    genericError: 'त्रुटि',
    expenseDeleteError: 'खर्च हटाने में त्रुटि',
    quantity: 'मात्रा',
    edit: 'संपादित करें',
    quantityPlaceholderExample: 'जैसे: 50',
    sellingPricePlaceholderExample: 'जैसे: 2000',

    cropInfo: 'फसल जानकारी',
    crop: 'फसल',
    land: 'जमीन',
    duration: 'अवधि',
    status: 'स्थिति',
    financialSummary: 'वित्तीय सारांश',
    totalCost: 'कुल खर्च',
    totalIncome: 'कुल आय',
    netProfit: 'शुद्ध लाभ',
    netLoss: 'शुद्ध हानि',
    addExpense: 'खर्च जोड़ें',
    completeCrop: 'फसल पूर्ण करें',
    generatePDF: 'PDF बनाएं',
    deleteCrop: 'फसल हटाएं',
    expenseDetails: 'खर्च का विवरण',
    noExpensesYet: 'अभी तक कोई खर्च नहीं जोड़ा गया',
    addFirstExpense: 'पहला खर्च जोड़ें',
    byType: 'प्रकार के अनुसार खर्च',
    individualExpenses: 'व्यक्तिगत खर्च',
    completeCropTitle: 'फसल पूर्ण करें',
    productionQty: 'उत्पादन (मात्रा)',
    unit: 'इकाई',
    sellingPrice: 'विक्रय मूल्य (प्रति इकाई)',
    complete: 'पूर्ण करें',
    notFound: 'फसल नहीं मिली',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    downloadPdfAfterComplete: 'PDF डाउनलोड करने के लिए फसल पहले पूर्ण करें',

    addExpenseTitle: 'नया खर्च जोड़ें',
    editExpenseTitle: 'खर्च संपादित करें',
    backToCropDetails: 'फसल विवरण',
    dateLabel: 'तारीख',
    materialTypeLabel: 'सामग्री का प्रकार',
    materialNameLabel: 'सामग्री का नाम',
    tractorOwnerLabel: 'ट्रैक्टर मालिक का नाम',
    materialNamePlaceholder: 'जैसे: यूरिया, DAP, मजदूर आदि',
    tractorOwnerPlaceholder: 'जैसे: राम सिंह',
    hoursLabel: 'घंटे',
    personsLabel: 'व्यक्ति',
    quantityLabel: 'मात्रा',
    quantityPlaceholder: 'जैसे: 50',
    tractorHoursPlaceholder: 'जैसे: 2.5',
    unitLabel: 'इकाई',
    numberOfDaysLabel: 'दिनों की संख्या',
    daysPlaceholder: 'जैसे: 5',
    pricePerHourLabel: 'प्रति घंटा दर (₹)',
    pricePerPersonLabel: 'प्रति व्यक्ति दर (₹)',
    pricePerUnitLabel: 'प्रति इकाई कीमत (₹)',
    pricePlaceholder: 'जैसे: 250',
    totalAmountLabel: 'कुल राशि',
    laborTypeLabel: 'मजदूर का प्रकार',
    billPhotoLabel: 'बिल की फोटो (वैकल्पिक)',
    billPhotoHelp: 'JPG, PNG, या PDF (अधिकतम 5MB)',
    notesLabel: 'नोट (वैकल्पिक)',
    notesPlaceholder: 'कोई अतिरिक्त जानकारी...',
    addExpenseButton: 'खर्च जोड़ें',
    addingExpenseButton: 'जोड़ा जा रहा है...',
    updateExpenseButton: 'खर्च अपडेट करें',
    updatingExpenseButton: 'अपडेट हो रहा है...',
    fileSizeError: 'फाइल 5MB से बड़ी नहीं होनी चाहिए',
    quantityValidationError: 'मात्रा 0 से अधिक होनी चाहिए',
    priceValidationError: 'प्रति इकाई कीमत 0 से अधिक होनी चाहिए',
    addExpenseError: 'खर्च जोड़ने में त्रुटि',
    updateExpenseError: 'खर्च अपडेट करने में त्रुटि',
    loadExpenseError: 'खर्च लोड करने में त्रुटि',
    days: 'दिन'
  },
  mr: {
    appName: 'किसान प्रॉफिट मित्र',
    heroTitle: 'किसान प्रॉफिट मित्र',
    heroSubtitle: 'तुमची डिजिटल शेती डायरी',
    feature1: 'सर्व खर्च नोंदवा',
    feature2: 'नफा-तोटा मोजा',
    feature3: 'प्रत्येक पिकाची नोंद ठेवा',
    feature4: 'PDF अहवाल तयार करा',
    ctaStart: 'सुरू करा',
    ctaLogin: 'लॉगिन',
    footerTagline: 'भारतीय शेतकऱ्यांसाठी बनविलेले',

    loginTitle: 'लॉगिन करा',
    loginSubtitle: 'आपल्या खात्यात प्रवेश करा',
    mobileLabel: 'मोबाईल नंबर',
    mobilePlaceholder: '10 अंकी नंबर',
    passwordLabel: 'पासवर्ड',
    passwordPlaceholder: 'पासवर्ड टाका',
    loginButton: 'लॉगिन करा',
    loginButtonLoading: 'लॉगिन होत आहे...',
    loginError: 'लॉगिन त्रुटी',
    noAccount: 'खाते नाही?',
    signupHere: 'येथे नोंदणी करा',
    backHome: '← होम पेजवर परत जा',

    signupTitle: 'नवीन खाते तयार करा',
    signupSubtitle: 'नोंदणी करा',
    nameLabel: 'नाव',
    namePlaceholder: 'आपले नाव टाका',
    confirmPasswordLabel: 'पासवर्ड पुन्हा टाका',
    confirmPasswordPlaceholder: 'पासवर्ड पुन्हा टाका',
    signupButton: 'नोंदणी करा',
    signupButtonLoading: 'नोंदणी सुरू आहे...',
    passwordMismatch: 'पासवर्ड जुळत नाहीत',
    passwordTooShort: 'पासवर्ड किमान 6 अक्षरे असावा',
    signupError: 'नोंदणी त्रुटी',
    haveAccount: 'आधीच खाते आहे?',
    loginHere: 'येथे लॉगिन करा',

    welcomeUser: 'स्वागत आहे',
    logout: 'लॉगआउट',
    startNewCrop: 'नवीन पिक सुरू करा',
    activeCrops: 'चालू पिके',
    noActiveCrops: 'कोणतेही चालू पिक नाही. नवीन सुरू करा!',
    completedCrops: 'पूर्ण पिके',
    modalTitle: 'नवीन पिक सुरू करा',
    selectCrop: 'पिक निवडा (Crop)',
    startDate: 'सुरुवातीची तारीख',
    expectedDuration: 'अनुमानित कालावधी (महिने)',
    landArea: 'जमिनीचे क्षेत्रफळ',
    landPlaceholder: 'उदा: 2.5',
    cancel: 'रद्द करा',
    create: 'तयार करा',
    durationPlaceholder: 'उदा: 4',
    months: 'महिने',
    startLabel: 'सुरुवात',
    viewDetails: 'तपशील पहा →',
    notAvailable: 'उपलब्ध नाही',
    areaValidation: 'जमिनीचे मूल्य योग्य भरा (>0)',
    durationValidation: 'कालावधी महिन्यांमध्ये योग्य भरा',
    createCropError: 'पिक तयार करताना त्रुटी',
    pdfRequiresCompletion: 'PDF डाउनलोडसाठी आधी पिक पूर्ण करा.',
    deleteCropConfirm: 'ही पिक हटवू इच्छिता?',
    deleteExpenseConfirm: 'हा खर्च हटवू?',
    genericError: 'त्रुटी',
    expenseDeleteError: 'खर्च हटविताना त्रुटी',
    quantity: 'प्रमाण',
    edit: 'संपादित करा',
    quantityPlaceholderExample: 'उदा: 50',
    sellingPricePlaceholderExample: 'उदा: 2000',

    cropInfo: 'पिक माहिती',
    crop: 'पिक',
    land: 'जमीन',
    duration: 'कालावधी',
    status: 'स्थिती',
    financialSummary: 'आर्थिक सारांश',
    totalCost: 'एकूण खर्च',
    totalIncome: 'एकूण उत्पन्न',
    netProfit: 'निव्वळ नफा',
    netLoss: 'निव्वळ तोटा',
    addExpense: 'खर्च जोडा',
    completeCrop: 'पिक पूर्ण करा',
    generatePDF: 'PDF तयार करा',
    deleteCrop: 'पिक हटवा',
    expenseDetails: 'खर्च तपशील',
    noExpensesYet: 'अजून कोणताही खर्च जोडलेला नाही',
    addFirstExpense: 'पहिला खर्च जोडा',
    byType: 'प्रकारानुसार खर्च',
    individualExpenses: 'वैयक्तिक खर्च',
    completeCropTitle: 'पिक पूर्ण करा',
    productionQty: 'उत्पादन (प्रमाण)',
    unit: 'एकक',
    sellingPrice: 'विक्री दर (प्रति एकक)',
    complete: 'पूर्ण करा',
    notFound: 'पिक सापडले नाही',
    backToDashboard: 'डॅशबोर्डवर परत जा',
    downloadPdfAfterComplete: 'PDF साठी आधी पिक पूर्ण करा',

    addExpenseTitle: 'नवीन खर्च जोडा',
    editExpenseTitle: 'खर्च संपादित करा',
    backToCropDetails: 'पिक तपशील',
    dateLabel: 'तारीख',
    materialTypeLabel: 'साहित्य प्रकार',
    materialNameLabel: 'साहित्य नाव',
    tractorOwnerLabel: 'ट्रॅक्टर मालकाचे नाव',
    materialNamePlaceholder: 'उदा: युरिया, DAP, मजूर इत्यादी',
    tractorOwnerPlaceholder: 'उदा: राम सिंह',
    hoursLabel: 'तास',
    personsLabel: 'व्यक्ती',
    quantityLabel: 'प्रमाण',
    quantityPlaceholder: 'उदा: 50',
    tractorHoursPlaceholder: 'उदा: 2.5',
    unitLabel: 'एकक',
    numberOfDaysLabel: 'दिवसांची संख्या',
    daysPlaceholder: 'उदा: 5',
    pricePerHourLabel: 'प्रति तास दर (₹)',
    pricePerPersonLabel: 'प्रति व्यक्ती दर (₹)',
    pricePerUnitLabel: 'प्रति एकक किंमत (₹)',
    pricePlaceholder: 'उदा: 250',
    totalAmountLabel: 'एकूण रक्कम',
    laborTypeLabel: 'मजुरांचा प्रकार',
    billPhotoLabel: 'बिलाचा फोटो (पर्यायी)',
    billPhotoHelp: 'JPG, PNG, किंवा PDF (कमाल 5MB)',
    notesLabel: 'नोंदी (पर्यायी)',
    notesPlaceholder: 'कोणतीही अतिरिक्त माहिती...',
    addExpenseButton: 'खर्च जोडा',
    addingExpenseButton: 'जोडत आहे...',
    updateExpenseButton: 'खर्च अपडेट करा',
    updatingExpenseButton: 'अपडेट करत आहे...',
    fileSizeError: 'फाइल 5MB पेक्षा मोठी नसावी',
    quantityValidationError: 'प्रमाण 0 पेक्षा जास्त असावे',
    priceValidationError: 'प्रति एकक किंमत 0 पेक्षा जास्त असावी',
    addExpenseError: 'खर्च जोडताना त्रुटी',
    updateExpenseError: 'खर्च अपडेट करताना त्रुटी',
    loadExpenseError: 'खर्च लोड करताना त्रुटी',
    days: 'दिवस'
  }
};

const LanguageContext = createContext({ lang: 'en', setLang: () => {}, t: (key) => key });

export const LanguageProvider = ({ children }) => {
  const [lang, setLangState] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    return localStorage.getItem('kpm-lang') || 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('kpm-lang', lang);
    }
  }, [lang]);

  const setLang = (value) => {
    setLangState(value);
  };

  const t = useMemo(() => {
    return (key) => translations[lang]?.[key] || translations.en[key] || key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, setLang, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
